version: '3.4'
services:

  backend:
    image: vjaos/tasky-backend
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  postgres:
    restart: always
    image: postgres
    volumes:
      - postgres:/data/pgdata
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"

volumes:
  pgadmin:
  postgres:
